name = "GradedRingUtilities"
uuid = "ac2b5ee4-d872-4ff4-b600-35f8f75c8465"
authors = ["JJ Garzella <jjgarzella@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
